#!/bin/sh

trap 'kill 0' EXIT

control_fifo=/tmp/shell-player-commands.fifo
info_fifo=/tmp/shell-player-info.fifo
server_rx_fifo=/tmp/shell-player-web-controller-server_rx.fifo
server_tx_fifo=/tmp/shell-player-web-controller-server_tx.fifo
rm -f "$server_rx_fifo" "$server_tx_fifo"
mkfifo "$server_rx_fifo" "$server_tx_fifo"
port=8080
ip="$(ip route get 1 | sed -n 's/.*src \([^ ]*\).*/\1/p')" # linux only

printf 'Access controller on: %s:%s\n' "$ip" "$port"

send_cmd() {
  printf '%s\n' "$1" > "$control_fifo"
}

dump_request_content() {
  printf 'HTTP/1.1 200 OK\r\n\r
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>shell-player</title>
  </head>
  <body>
    <header>
      %s
    </header>
    <form method="POST">
      <input type="submit" name="action" value="previous">
      <input type="submit" name="action" value="next">
      <input type="submit" name="action" value="loop">
      <input type="submit" name="action" value="pause">
      <input type="submit" name="action" value="quit">
    </form>
  </body>
</html>
' "$(fetch_info)"
}

fetch_info() {
  send_cmd info
  sed '
    1{
      s|.*|<h1>&</h1>|
      n
    }
    s|.*|<h2>&</h2>|
  ' "$info_fifo"
}

run_server() {
  while true; do
    nc -l -p "$port" < "$server_tx_fifo" > "$server_rx_fifo"
  done &
  server_pid="$!"
}

process_request() {
  exec 3> "$server_tx_fifo"
  exec 4< "$server_rx_fifo"

  valid=false
  content_length=0
  payload=
  while IFS= read -r line; do
    case "$line" in
      'GET / HTTP/1.1'*|'POST / HTTP/1.1'*)
        method="${line%% *}"
        valid=true
        ;;
      "$(printf '\r')")
        if "$valid"; then
          if [ "$method" = POST ]; then
            payload="$(dd bs=1 count="$content_length" status=none <&4)"
            if [ -n "$payload" ]; then
              send_cmd "${payload#action=}"
            fi
          fi
          exec 4<&-
          dump_request_content
        else
          printf 'HTTP/1.1 404 Not Found\r\n\r\n'
        fi >&3
        exec 3>&-
        ;;
      Content-Length:*)
        line="${line%?}" # remove \r
        content_length="${line#* }"
        ;;
    esac
  done <&4

}

run_server

while process_request; do
  :
done
